[package]
name = "trimage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
spade = "*"
rand = "*"
clap = "2.34.0"
